### ISSUE TITLE
# [CLUSTER-L1] Incorrect state tracked on Cluster

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#268]
# Description

The `lzChainId` address is set on the constructor in the `cluster` contract:

```
 constructor(uint32 _lzChainId, address _owner) {
        lzChainId = _lzChainId;
        transferOwnership(_owner);
    }
``` 

but it is not tracked via emitting the already existing event called `LzChainUpdate`

Usually with events you should be able to track the exact inital state, which in this case the first one, would be missing.

# Recommendation

Emit the event on the constructor:

```diff
 constructor(uint32 _lzChainId, address _owner) {
+       emit LzChainUpdate(lzChainId, _lzChainId);
        lzChainId = _lzChainId;
        transferOwnership(_owner);
    }
``` 
# Resolution

**Comment by cryptotechmaker** [comment]
Should be fixed here https://github.com/Tapioca-DAO/tapioca-periph/pull/267/commits/bd7c050e68eb0b443d4c17630d40d36ba76a0aa6

**Comment by maarcweiss** [comment]
Fixed
