### ISSUE TITLE
# [PMH-L1] Incorrect state tracked on Pearlmit

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#269]
# Description

The `pearlmit` address is set on the constructor in the `PearlmitHandler` contract:

```
 constructor(IPearlmit _pearlmit) { 
        pearlmit = _pearlmit;
    }
``` 

but it is not tracked via emitting the already existing event called `PearlmitUpdated`

Usually with events you should be able to track the exact inital state, which in this case the first one, would be missing.

# Recommendation

Emit the event on the constructor:

```diff
   constructor(IPearlmit _pearlmit) { 
+       emit PearlmitUpdated(pearlmit, _pearlmit);
        pearlmit = _pearlmit;
    }
``` 
# Resolution

**Comment by cryptotechmaker** [comment]
Should be fixed here https://github.com/Tapioca-DAO/tapioca-periph/pull/267/commits/bd7c050e68eb0b443d4c17630d40d36ba76a0aa6

**Comment by maarcweiss** [comment]
Fixed
