### ISSUE TITLE
# [GLOBAL-L1] Un-used imports across the repo

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#270]
# Description
The following import are un-used, delete them:

- MagnetarAssetModule:

import {IERC721} from "@openzeppelin/contracts/token/ERC721/IERC721.sol"; 
import {TapiocaOmnichainEngineCodec} from "tapioca-periph/tapiocaOmnichainEngine/TapiocaOmnichainEngineCodec.sol"; 

- MagnetarBaseModule:

import {OFTMsgCodec} from "@layerzerolabs/lz-evm-oapp-v2/contracts/oft/libs/OFTMsgCodec.sol"; 
import {IMessagingChannel} from "@layerzerolabs/lz-evm-protocol-v2/contracts/interfaces/IMessagingChannel.sol";

- MagnetarCollateralModule:

import {IMarket, Module} from "tapioca-periph/interfaces/bar/IMarket.sol"; 
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol"; 

- MagnetarOptionModule:

import {IMarketHelper} from "tapioca-periph/interfaces/bar/IMarketHelper.sol";
import {ITOFT} from "tapioca-periph/interfaces/oft/ITOFT.sol"; 

# Resolution

**Comment by cryptotechmaker** [comment]
Should be fixed here https://github.com/Tapioca-DAO/tapioca-periph/pull/267/commits/bd7c050e68eb0b443d4c17630d40d36ba76a0aa6

**Comment by maarcweiss** [comment]
Fixed
