### ISSUE TITLE
# [GLOBAL-L2] Very inefficient architecture

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#271]
# Description
The function:

```
  function _getRevertMsg(bytes memory _returnData) internal pure returns (string memory) {
        if (_returnData.length > 1000) return "Market: reason too long";
        // If the _res length is less than 68, then the transaction failed silently (without a revert message)
        if (_returnData.length < 68) return "Market: no return data";
        // solhint-disable-next-line no-inline-assembly
        assembly {
            // Slice the sighash.
            _returnData := add(_returnData, 0x04)
        }
        return abi.decode(_returnData, (string)); // All that remains is the revert string
    }
```

is literally declared separately in every different module, while it is already existent as a library in Tapioca-Bar, by the name of `RevertMsgDecoder`.

# Recommendation
Ideally call the library from bar directly, if not add the same library to periph, otherwise you are just adding an extra repeated 100nsloc.

# Resolution

**Comment by cryptotechmaker** [comment]
Should be fixed here https://github.com/Tapioca-DAO/tapioca-periph/pull/267/commits/bd7c050e68eb0b443d4c17630d40d36ba76a0aa6

**Comment by maarcweiss** [comment]
See my comment here: https://github.com/Tapioca-DAO/tapioca-periph/commit/bd7c050e68eb0b443d4c17630d40d36ba76a0aa6#r141933001

**Comment by cryptotechmaker** [comment]
Fixed comment https://app.graphite.dev/github/pr/Tapioca-DAO/Tapioca-bar/409/chore-small-QA-fixes @maarcweiss

**Comment by maarcweiss** [comment]
Fixed
