### ISSUE TITLE
# [MBM-L1] Pearlmit is left unset which will make the execution flow revert

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#287]
# Description

In the `MagnetarBaseModule` contract the `MagnetarStorage` is being initialized with a `0 address` for Pearlmit, which will leave the variable un-initialized and will make transactions revert:

```
    constructor() MagnetarStorage(IPearlmit(address(0))) {} 
```

# Recommendation

Pass the correct `IPearlmit` address on the constructor

```diff
-   constructor() MagnetarStorage(IPearlmit(address(0))) {}
+   constructor(address pearlmit) MagnetarStorage(IPearlmit(pearlmit)) {}  
``` 
# Resolution

**Comment by cryptotechmaker** [comment]
https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/299/Marc-MBM-L1-Pearlmit-is-left-unset-which-will-make-the-execution-flow-revert-287-CU-86dtjb92v
