### ISSUE TITLE
# [MS-M1] `toeHelper` is deployed once per every module which is unnecessary and will increase exponentially deployment costs 

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#296]
# Description

`toeHelper` is deployed once per every module which is unnecessary and will increase exponentially deployment costs.

Because `toeHelper` is deployed in `MagnetarStorage` which is inherited by every single module:

```
  constructor(IPearlmit _pearlmit) PearlmitHandler(_pearlmit) {
        toeHelper = new TapiocaOmnichainEngineHelper(); 
    }
```

This will cause that we have to deploy a logic heavy contract 4 times more than we need, possibly exceeding 4 figs in deployment costs

# Recommendation

Instead of deploying the `toeHelper` contract inside Magnetar storage, deploy it independently only once and set individually in every module as a state variable.

# Resolution

**Comment by cryptotechmaker** [comment]
https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/302/Marc-MS-M1-toeHelper-is-deployed-once-per-every-module-which-is-unnecessary-and-will-increase-exponentially-deployment-costs-296-CU-86dtje2tb
