### ISSUE TITLE
# [GLOBAL-L5] Architectural improvement on the Magnetar Modules

### ISSUE THREAD

**Issue by maarcweiss** [Tapioca-DAO/tapioca-periph#297]
# Description

The `MagnetarAssetModule` contract should not exist in Magnetar as the only action, which is `depositRepayAndRemoveCollateralFromMarket` 
is more suitable to be in `MagnetarCollateralModule`. 

# Recommendation

Remove the `MagnetarAssetModule` and declare the `depositRepayAndRemoveCollateralFromMarket` function in `MagnetarCollateralModule`

# Resolution

**Comment by cryptotechmaker** [comment]
https://app.graphite.dev/github/pr/Tapioca-DAO/tapioca-periph/303/Marc-GLOBAL-L5-Architectural-improvement-on-the-Magnetar-Modules-297-CU-86dtje2tp
